#!/usr/bin/env bash
# This scripts transfer a file from client to server using scp

# Check if the required number of arguments is passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables
file_path=$1
server_ip=$2
uname=$3
ssh_key_path=$4

# Transfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$uname"@"$server_ip":~/
