#!/usr/bin/env bash
# This script configures NGINX to perform a 301 redirection using sed

# Update package list
apt update

# Install NGINX
apt install -y nginx

# Allowing NGINX on firewall
ufw allow 'Nginx HTTP'

# Set up 301 redirection using sed
sed -i '/server_name _;/a \\n    location \/redirect_me {\n        rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n    }' /etc/nginx/sites-available/default

# Test NGINX configuration
nginx -t

# Restart NGINX
service nginx restart
