#!/usr/bin/env bash
# This script installs and configures nginx

# Update package list
apt update

# Install NGINX
apt install -y nginx

# Allowing NGINX on firewall
ufw allow 'Nginx HTTP'

# Create a custom 404 error page containing the specified string
echo 'Ceci n'"'"'est pas une page' > /usr/share/nginx/html/404.html

# Configure NGINX to use the custom 404 page
sed -i '/server_name _;/a \\n    error_page 404 /404.html;\n    location = /404.html {\n        root /usr/share/nginx/html;\n        internal;\n    }\n    location = /404 {\n        return 404 "Ceci n'"'"'est pas une page";\n    }' /etc/nginx/sites-available/default

# Test NGINX configuration
nginx -t

# Restart NGINX
service nginx restart
