#!/usr/bin/env bash
# This script fulfilss the below requirements
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
# Write 0-custom_http_response_header so that it configures a brand new Ubuntu machine to the requirements asked in this task
# Ignore SC2154 for shellcheck

# Update package list
apt update

# Install nginx
apt install -y nginx

# Create directories
mkdir -p /data/web_static/releases/test/

# Create fake html file
touch /data/web_static/releases/test/index.html

# Write fake html file
echo "Holberton School" | tee /data/web_static/releases/test/index.html

# Create symbolic link
ln -sf /data/web_static/releases/test/ /data/web_static/current

# Change ownership of /data/
chown -R ubuntu:ubuntu /data/

# Update Nginx configuration to serve the content of /data/web_static/current/ to hbnb_static
sed -i "/listen 80 default_server;/a location /hbnb_static/ { alias /data/web_static/current/; }" /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
