#!/usr/bin/env bash
# This script installs and configures nginx

# Update package list
apt update

# Install nginx
apt install -y nginx

# Allowing nginx on firewall
ufw allow 'Nginx HTTP'

# Create a temporary HTML file containing "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Ensure Nginx is listening on port 80
server_block_path="/etc/nginx/sites-available/default"
sed -i 's/listen 80 default_server;/listen 80;/g' "$server_block_path"

# Add custom header to Nginx configuration
sed -i '/listen 80 default_server;/a add_header X-Served-By: $hostname;' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
