#!/usr/bin/env bash
# This script installs and configures an HAProxy load balancer

# Update package list
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null << 'EOF'
global
    log /dev/log local0
    log /dev/log local1 notice
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 326145-web-01:80 check
    server web-02 326145-web-02:80 check
EOF

# Ensure HAProxy can be managed via an init script
sudo systemctl enable haproxy

# Restart HAProxy to apply changes
sudo systemctl restart haproxy
