#!/usr/bin/env bash
# This script installs and configures an HAProxy load balancer

# Update package list
apt-get update -y

# Install HAProxy
apt-get install -y haproxy

# Configure HAProxy
cat <<EOT | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
frontend http-in
        bind *:80
        default_backend servers
backend servers
    balance roundrobin
    server 326145-web-01 100.27.2.172:80 check
    server 326145-web-02 100.25.158.175:80 check
EOT

# Ensure correct hostnames (optional if not already configured)
sudo hostnamectl set-hostname 326145-lb-01

# Start HAProxy
sudo systemctl start haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Reload HAProxy configuration
sudo systemctl reload haproxy

# Check the status of HAProxy and configured servers
echo "HAProxy Status:"
sudo systemctl status haproxy --no-pager

echo "Configured Servers:"
sudo grep -E 'server [0-9]+-web-[0-9]+ [0-9.]+:[0-9]+' /etc/haproxy/haproxy.cfg | awk '{print $2}'

