#!/usr/bin/env bash
# MySQL backup script

# Write a Bash script that generates a MySQL dump and creates a compressed archive out of it.

# Requirements:
# The MySQL dump must contain all your MySQL databases
# The MySQL dump must be named backup.sql
# The MySQL dump file has to be compressed to a tar.gz archive
# This archive must have the following name format: day-month-year.tar.gz
# The user to connect to the MySQL database must be root
# The Bash script accepts one argument that is the password used to connect to the MySQL database


# Get current date
current_date=$(date +%d-%m-%Y)

# MySQL dump command
mysqldump -u root -p"$1" --all-databases > backup.sql

# Compress the dump file
tar -czvf "$current_date.tar.gz" backup.sql
