#!/usr/bin/env bash
# This bash script does the following:
#     When passing the argument start:
#         Starts manage_my_process
#         Creates a file containing its PID in /var/run/my_process.pid
#         Displays manage_my_process started
#     When passing the argument stop:
#         Stops manage_my_process
#         Deletes the file /var/run/my_process.pid
#         Displays manage_my_process stopped
#     When passing the argument restart
#         Stops manage_my_process
#         Deletes the file /var/run/my_process.pid
#         Starts manage_my_process
#         Creates a file containing its PID in /var/run/my_process.pid
#         Displays manage_my_process restarted
#     Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed

# Check the argument passed to the script
case "$1" in
    start)
        ./manage_my_process &
        echo $$ > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        kill "$(pgrep -f /manage_my_process)"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        kill "$(pgrep -f /manage_my_process)"
        rm /var/run/my_process.pid
        ./manage_my_process &
        echo $$ > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
