#!/usr/bin/env bash
# This script reads more data from /etc/password

# Read the /etc/passwd file line by line
while IFS=: read -r username _ uid gid info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
    echo "$uid's place is protected by the passcode x, more info about the user here: $info"
done < /etc/passwd
