#!/usr/bin/env bash
# run nginx user for Nginx

# Stop Nginx if it's running
sudo service nginx stop

# Modify Nginx configuration to run as nginx user
sudo sed -i 's/^user .*;/user nginx;/' /etc/nginx/nginx.conf

# change ownership and permissions of config file
sudo chmod 700 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf

# Modify Nginx configuration to listen on all active IPs on port 8080
sudo sed -i 's/^listen .*;/listen 8080;/g' /etc/nginx/sites-available/default

# Start Nginx service
pkill apache2
sudo -u nginx service nginx restart
