#!/usr/bin/env bash
# run nginx user for Nginx
sudo pkill apache2
sudo sed -i "s/listen 80/listen 8080/" /etc/nginx/sites-available/default
sudo sed -i "s/listen \[::\]:80/listen \[::\]:8080/" /etc/nginx/sites-available/default
sudo chmod 0644 /etc/nginx/nginx.conf
su nginx -c "service nginx start"
